persistence:
  worker:
    enabled: true
    # existingClaim: ""
    size: 8Gi
    storageClass: "scale-zfs"
  logs:
    # Container based log search and analytics stack recommended
    enabled: false
    # existingClaim: ""
    size: 8Gi
    # storageClass: "scale-zfs"